### ISSUE TITLE
Diving Wishlist

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#1]
## Value Proposition

**As a** user
**I need** to add dive locations to a wishlist
**to be able to** remember them easily

## Description

![WishlistPage](https://user-images.githubusercontent.com/94636438/156617329-557ec6ab-d23c-45b0-bfd1-c57acedef3c4.png)

## Acceptance Criteria

- [x] The user is presented a form and an empty wishlist
- [x] If the wishlist is empty a message should be shown to the user
- [x] User can add an item to the wishlist by entering the dive destination and some notes into a form
- [x] Destination and notes are required for adding a new item
- [x] After submitting the form both input fields will be reset and the item will be added to the top of the wishlist
- [x] Every item on the wishlist should be displayed with a destination and notes

## Tasks

- [x] Global Styles
- [x] Create component/DiveWish
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
- [x] Create component/Wishlist
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
- [x] Create component/Button
    - [x] Storybook
    - [x] Add styled-components
- [x] Create component/AddDiveWish
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
 - [x] Add to App 
- [x] Check accessibility
- [x] Check on mobile phone
