### ISSUE TITLE
Archive items

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#12]
## Value Proposition

**As a** user
**I need** to tick off items on my wishlist
**to be able to** keep my diving wishlist up to date

## Description

![Archive](https://user-images.githubusercontent.com/94636438/157888840-b60da6ca-78f7-44f4-94a3-92eb174e1354.png)

## Acceptance Criteria

- [x] Each item on the wishlist shows a button to tick off the item
- [x] When ticked off, the item will be moved from the wishlist to the archive
- [x] If a ticked off item is bookmarked, it will be removed from the bookmarks page
- [x] On the wishlist page there is a button to navigate to the archive, which is only visible if there are archived items
- [x] On the archive page:
    - [x] All ticked-off items will be shown
    - [x] Archived items do not show a bookmark button
    - [x] By clicking the tick-off button again, the item will be moved from the archive back to the wishlist
    - [x] At the top of the page is a button to navigate back to the wishlist

## Tasks

- [x] Update component/DiveWish
    - [x] Update tests
    - [x] Update Storybook
    - [x]  Add/adjust styled-components
- [x] Update component/WishlistPage
    - [x] Update tests
    - [x] Update Storybook
    - [x]  Add/adjust styled-components
- [x] Update component/BookmarksPage
- [x] Create component/ArchivePage
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
- [x] Update app
    - [x] Update React Router
- [x] Check accessibility
- [x] Check on mobile phone
