### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#13]
## Value Proposition

**As a** user
**I need** to log in to the app
**to be able to** use the app with more than one person on the same device

## Description

<img width="524" alt="Login1" src="https://user-images.githubusercontent.com/94636438/158085347-83fbc1eb-d9bc-4474-86dd-7df239d19218.png">
<img width="516" alt="Login2" src="https://user-images.githubusercontent.com/94636438/158085350-a2af2295-cd65-477b-8a86-65e565634923.png">

## Acceptance Criteria

- [ ] On starting the app the user is presented a login screen
- [ ] On the login screen:
    - [ ] There is a form with to input fields for email and password and a login button
    - [ ] Underneath the form is a link to the signup form if the user has no account yet and another link to reset the password via email
    - [ ] If email or password are entered wrong or do not exist, an error message is shown to the user
    - [ ] On successful login the user is redirected to the wishlist page
- [ ] On the signup screen:
    - [ ] There is a form with three input fields for email, password and confirming the password as well as a signup button
    - [ ] Underneath the form is a link to go the login page if the user has already an account
    - [ ] On successful signup the user is redirected to the wishlist page
    - [ ] If the two passwords do not match or there is an error while creating the account, an error message is shown to the user
- [ ] On the reset-password screen:
    - [ ] There is a form with an input field for the email and a button to reset the password
    - [ ] Underneath the form is a link to go the login page and to the signup page
    - [ ] On successful password reset a confirmation message will be shown to the user
    - [ ] The user will receive an email to change the password
    - [ ] If no existing email address is entered, an error message will be shown to the user
- [ ] All pages will show a logout button in the upper right corner
- [ ] By clicking on the logout button the user will be logged out and redirected to the login page
- [ ] Without a login the user only has access to the login, signup and reset-password page

## Tasks

- [ ] Implement Authentication with Firebase
    - [ ] Add environmental variables
    - [ ] Create Firebase config
    - [ ] Create Authentification Context
    - [ ] Add AuthProvider to App
- [ ] Create component/Login
    - [ ]  Storybook
    - [ ] Write tests
    - [ ] Add styled-components
- [ ] Create component/Signup
    - [ ]  Storybook
    - [ ] Write tests
    - [ ] Add styled-components
- [ ] Create component/ForgotPassword
    - [ ]  Storybook
    - [ ] Write tests
    - [ ] Add styled-components
- [ ] Create component/PrivateRoutes
- [ ] Update component/Header
    - [ ] Add logout button
    - [ ] Update tests
    - [ ] Adjust styled-components
- [ ] Add to App
    - [ ] Update React-Router
- [ ] Check accessibility
- [ ] Check on mobile phone
