### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#17]
## Value Proposition

**As a** user
**I need** to save my diving wishlist in a database
**to be able to** access my wishlist from anywhere

## Acceptance Criteria

- [ ] User data will be stored in a database (id, email, Firebase user-id)
- [ ] Wishlist data will be stored in a database (id, destination, notes, author, bookmarked, archived, time created)

## Tasks

- [ ] Setup Vercel - serverless functions
    - [ ] Create route /api/users
    - [ ] Create route api/posts
- [ ] Setup mongoDB Atlas
    - [ ] Add needed IP addresses
    - [ ] Add URI to local .env and Vercel
    - [ ] Create schema for users: models/User.mjs
    - [ ] Create schema for posts: models/Post.mjs
    - [ ] Create /lib/dbConnect.mjs
    - [ ] Connect to mongoDB
 - [ ] Update component/SignupForm
 - [ ] Update App
