### ISSUE TITLE
Dive Request

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#18]
## Value Proposition

**As a** user
**I need** to post a dive request
**to be able to** find a dive buddy for my next holiday

## Description

![DiveRequest](https://user-images.githubusercontent.com/94636438/159179759-f78362a7-6acf-41b0-ac63-02bb48f99f9f.png)

## Acceptance Criteria

- [x] The Signup Page shows an additional input field for the full name of the user
- [x] The page to add a dive wish will be repurposed to add a dive request
    - [x] Additionally to the destination and notes, there is an input field to pick a travel date
- [x] The page with the wishlist will be repurposed to show all dive requests
    - [x] Each request will show the name of the user, posting date, notes, travel dates and destination as well as an icon to  bookmark the post and to contact the user
    - [x] Own posts can be edited and deleted but will not show bookmark and contact icon

## Tasks

- [x] Update component/LoginSignupForm
    - [x] Adjust tests
    - [x] Update Storybook
    - [x] Adjust styled-components
- [x] Save new user with full name in database
    - [x] Update models/User
    - [x] Update page/StartScreen 
- [x] Rename and update component/DiveWishForm to component/RequestForm
    - [x] Adjust tests
    - [x] Update Storybook
    - [x] Adjust styled-components
- [x] Rename page/AddWishPage to page/AddRequestPage
    - [x] Adjust tests
- [x] Rename page/EditWishPage to page/EditRequestPage
    - [x] Adjust tests
- [x] Rename and update component/DiveWish to component/Request
    - [x] Adjust tests
    - [x] Update Storybook
    - [x] Adjust styled-components
- [x] Rename page/WishlistPage to page/SearchPage
    - [x] Adjust tests
- [x] Update component/Navigation
- [x] Update App
    - [x] Update React Router 
- [x] Check accessibility
- [x] Check on mobile phone
