### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#19]
## Value Proposition

**As a** user
**I need** to have a profile page
**to be able to** inform others about myself

## Description

![Profile1](https://user-images.githubusercontent.com/94636438/159179103-1b151460-2e95-496f-936b-ab07d7fb881c.png)

![Profile2](https://user-images.githubusercontent.com/94636438/159179106-7f27d970-4997-4841-b498-b863d067ffb2.png)

## Acceptance Criteria

- [x] The navigation shows an icon for the search, favorites, add request and profile page
    - [x] Icon is filled if page is active
- [x] Own profile page can be reached through the navigation
    - [x] There is a link to a page, which shows all posts of the user (only visible if the user has posted anything)
- [x] The page with the posts of the user shows archived and not archived posts
- [x] Users can reach the profile page of other users by clicking on their name in the posts

## Tasks

- [x] Update component/Navigation
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Update component/Request
    - [x] Adjust tests if necessary
    - [x] Adjust styled-components if necessary
- [x] Update page/SearchPage
    - [x] Adjust tests if necessary
    - [x] Adjust styled-components if necessary
- [x] Create page/ProfilePage
    - [x] Write tests
    - [x] Add styled-components
- [x] Rename and update page/ArchivePage to page/UserRequestsPage
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Add to App
    - [x] Update React Router 
- [x] Check on mobile phone
