### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#2]
## Value Proposition

**As a** user
**I need** to have the form on a separate page and be able to navigate between my wishlist and the form
**to be able to** have a better overview over my wishlist

## Description

![Navigation](https://user-images.githubusercontent.com/94636438/157210030-e0ea74ff-2890-4451-a5e9-3d69e3ee2d57.png)

## Acceptance Criteria

- [x] Navigation should be always visible for user
- [x] Navigation should be displayed at the bottom of the viewport
- [x] Navigation should show which page the user is currently looking at

## Tasks

- [x] Change component/AddDiveWish to page/AddWishPage
    - [x] Update tests
    - [x] Update Storybook
- [x] Change component/Wishlist to page/WishlistPage
    - [x] Update tests
    - [x] Update Storybook
- [x] Create component/Navigation
    - [x] Write tests
    - [x] Storybook
    - [x] styled-components
- [x] Add to App
    - [x] Add React Router
- [x] Check accessibility
- [x] Check on mobile phone
