### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#20]
## Value Proposition

**As a** user
**I need** to edit my profile page
**to be able to** keep my personal information up-to-date

## Description

![EditProfile](https://user-images.githubusercontent.com/94636438/159184277-936f97ce-9964-439d-a110-79d9ed7fa432.png)

## Acceptance Criteria

- [x]  The profile page shows an icon to edit the profile
- [x] By clicking on the edit-icon the user will be redirected to the edit-profile-page
- [x] On the edit-page a form will be shown, prefilled with the personal information
- [x] After changing the personal information and submitting the form the user will be redirected to the profile page
- [x] On the top of the edit-pprofile-page an icon will be displayed to abort the editing process
- [x] By clicking the abort-icon the user will be redirected to the profile page

## Tasks

- [x] Update page/ProfilePage
    - [x] Update test
    - [x]  Adjust styled-components
- [x] Create page/EditProfilePage
    - [x] Write tests
    - [x] Add styled-components   
 - [x] Update App
     - [x] Update React Router
 - [x] Check accessibility
 - [x] Check on mobile phone
