### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#21]
## Value Proposition

**As a** user
**I need** to upload pictures to my profile
**to be able to** show other users who I am

## Description

<img width="535" alt="PictureUpload" src="https://user-images.githubusercontent.com/94636438/159189185-ffa9ce03-c58c-476d-a85e-f387632d7c21.png">

## Acceptance Criteria

- [x] The edit-page shows  an icon to upload a profile and a background picture
- [x] By clicking on the icon a popup will appear to choose a picture from the computer of the user
- [x] Once uploaded the picture will appear on the edit-page and be saved automatically
- [x] Each dive request shows the profile picture next to the users name
- [x] If the user has no pictures uploaded, placeholder pictures will be shown in the dive requests and profile page

## Tasks

- [x] Implement image upload via Cloudinary
- [x] Update page/ProfilePage
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Update page/EditProfilePage
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Update component/Request
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Check accessibility
- [x] Check on mobile phone
