### ISSUE TITLE
Personal bookmarks

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#26]
## Value Proposition

**As a** user
**I need** to see only my own bookmarked posts and not the once bookmarked by other users
**to be able to** find my favorite posts more quickly.

## Description

The bookmark page shows only the posts marked by the current user.

## Acceptance Criteria

- [ ] The bookmarked page shows only the posts bookmarked by the current user
- [ ] If the user has no posts bookmarked, a message will be shown to the user

## Tasks

- [ ] Update page/BookmarksPage
    - [ ] Adjust tests
- [ ] Update App
- [ ] Check on mobile phone
