### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#27]
## Value Proposition

**As a** user
**I need** to search for a certain user or location
**to be able to** find my future dive buddy faster

## Description

<img width="605" alt="Searchbar" src="https://user-images.githubusercontent.com/94636438/160303424-415299b7-d299-41a0-9a47-54a967643942.png">

## Acceptance Criteria

- [x] The search page shows a search bar in the header and a navigation underneath to switch between the search pages
    - [x] Destination search: user can search for a certain location in all posts
    - [x] Buddies search: user can search for a certain name of a user

## Tasks

- [x] Create component/Searchbar
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
- [x] Create component/SubHeader
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
- [x] Create component/RequestsList
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
- [x] Create component/BuddiesList
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
- [x] Update page/Searchpage
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Update App
- [x] Check accessibility
- [x] Check on mobile phone
