### ISSUE TITLE
Location API

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#28]
## Value Proposition

**As a** user
**I need** to get suggestions while choosing my trip destination and my home location
**to be able to** find the place I want to choose faster

## Description

The input field for the destination of a request and the home location of a user will show location suggestions from an API while the user is typing. 

## Acceptance Criteria

- [x] On the request form the user will get suggestions while typing in a destination
    - [x] the selected location will be saved
    - [x] the user cannot choose any location which is not suggested by the API
    - [x] the user will be shown an error message when there is no location found by the API
- [x] On the edit profile page the user will get suggestions while typing in a home location
    - [x] the selected location will be saved
    - [x] the user cannot choose any location which is not suggested by the API
    - [x] the user will be shown an error message when there is no location found by the API

## Tasks

- [x] Update component/RequestForm
    - [x] Integrate geocoder from Mapbox
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Update page/EditProfilePage
    - [x] Integrate geocoder from Mapbox
    - [x] Adjust tests
    - [x] Adjust styled-components
- [x] Update App
- [x] Check accessibility
- [x] Check on mobile phone
