### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#29]
## Value Proposition

**As a** developer
**I need** clean code
**to be able to** maintain the app more easily

## Description

Refactoring of whole code

## Acceptance Criteria

- [ ] Refactoring of whole code

## Tasks

- [ ] Refactor code
    - [ ] move functions from App into custom hook
    - [ ] check that code is semantically correct
    - [ ] create components for styling purposes if necessary
