### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#3]
## Value Proposition

**As a** user
**I need** my wishlist to still be there after reloading the app
**to be able to** remember where I want to dive next

## Description

All items added to the wishlist by the user will be stored in the local storage.  

## Acceptance Criteria

- [x] After reloading the app the added items will be still shown in the wishlist

## Tasks

- [x] Create hook/LocalStorage
- [x] Update page/App
