### ISSUE TITLE
Restyling

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#33]
## Value Proposition

**As a** user
**I need** to have a properly styled app
**to be able to** use it on all my different devices

## Description

Adjust overall styling

## Acceptance Criteria

- [x] Adjust navigation and header, so that both are permanently visible on all mobile devices
- [x] Adjust AppGrid and body
- [x] Extract duplicates into components

## Tasks

- [x] Adjust component/Navigation
- [x] Adjust component/Header
- [x] Adjust component/Content
- [x] Integrate component/IconButton in component/Button
- [x] Extract duplicates into own components
- [x] Update Readme
