### ISSUE TITLE
Delete items from wishlist

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#4]
## Value Proposition

**As a** user
**I need** to delete an item from my wishlist
**to be able to** keep my wishlist up to date

## Description

![DeleteItem](https://user-images.githubusercontent.com/94636438/156619643-6e9d3d81-6cbd-462c-a985-a0abf65964d7.png)

## Acceptance Criteria

- [x] Each item on the wishlist will show an icon to delete the entry
- [x] By clicking on the delete-icon a modal will appear asking the user if he is sure to delete the item
    - [x] By clicking on the delete button the popup will close and the item will be removed from the wishlist
    - [x] By clicking on the undo button the popup will close but the item will remain on the wishlist

## Tasks

- [x] Create component/DeleteDialog
     - [x] Write tests
    - [x] Storybook
    - [x]  Add styled-components
- [x] Update component/DiveWish
    - [x] Update tests
    - [x] Update Storybook
    - [x]  Add/adjust styled-components 
 - [x] Update component/WishlistPage
    - [x] Update tests
    - [x] Update Storybook
    - [x]  Add/adjust styled-components
 - [x] Update App
 - [x] Check accessibility
 - [x] Check on mobile phone
