### ISSUE TITLE
Edit item on wishlist

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#5]
## Value Proposition

**As a** user
**I need** to edit an item from my wishlist
**to be able to** add notes to my items later on

## Description

![Edit](https://user-images.githubusercontent.com/94636438/157701721-b71608ce-6c3b-454b-b3e6-6128f4577a62.png)

## Acceptance Criteria

- [x]  Each item on the wishlist will show an icon to edit the entry
- [x] By clicking on the edit-icon the user will be redirected to the edit-page
- [x] On the edit-page a form will be shown with the information of the selected item
- [x] After changing the item and submitting the form the user will be redirected to the wishlist
- [x] The wishlist will include the updated item
- [x] On the top of the edit-page an icon will be displayed to abort the editing process
- [x] By clicking the abort-icon the user will be redirected to the wishlist

## Tasks

- [x] Create component/IconButton
   - [x] Storybook
   - [x] Add/adjust styled-components
- [x] Update component/DiveWish
    - [x] Update test
    - [x] Update Storybook
    - [x]  Add/adjust styled-components
- [x] Create component/DiveWishForm
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components 
- [x] Create component/EditWishPage
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components    
- [x] Update component/AddWishPage
    - [x] Update tests
    - [x] Update Storybook
    - [x] Add/Adjust styled-components 
 - [x] Change component/heading to component/Header
    - [x] Update Storybook
    - [x] Write tests
    - [x] Adjust styled-components    
 - [x] Update App
 - [x] Update Component/Navigation & React Router
 - [x] Check accessibility
 - [x] Check on mobile phone
