### ISSUE TITLE
Bookmark item on wishlist

### ISSUE THREAD

**Issue by ahohnsen** [ahohnsen/capstone-project#6]
## Value Proposition

**As a** user
**I need** to mark items on my wishlist
**to be able to** find them quickly

## Description
![Bookmarks1](https://user-images.githubusercontent.com/94636438/157653667-d9a6bc3f-84a9-42ae-bc9c-62ef822d16fc.png)

![Bookmarks2](https://user-images.githubusercontent.com/94636438/157653676-c7ca69fc-cea1-42e1-879b-2518e1666a07.png)

## Acceptance Criteria

- [x] Each item on the wishlist will show a button to mark the entry
- [x] The button should toggle with color
- [x] The navigation shows a button for the boomark-page
- [x] On the bookmark-page: 
    - [x] all bookmarked items are shown
    - [x] if a bookmark is removed, the item will no longer be shown on the bookmark-page
    - [x] If no items are bookmarked, the bookmark-page shows a message to the user that there are currently no bookmarked dive destinations

## Tasks

- [x] Update component/DiveWish
    - [x] Update tests
    - [x] Update Storybook
    - [x]  Add/adjust styled-components
- [x] Update component/WishlistPage
- [x] Create component/BookmarksPage
    - [x] Write tests
    - [x] Storybook
    - [x] Add styled-components
 - [x] Update component/Navigation
    - [x] Update tests
    - [x]  Add/adjust styled-components
- [x] Update app
    - [x] Update React Router
- [x] Give specific heading to all pages
    - [x] Adjust styled-components       
- [x] Check accessibility
- [x] Check on mobile phone
